
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db
    username: root
    password: password

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 5000