
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update

server:
  port: 5000