
account:
  min_balance: 1000


spring:
  security:
    user:
      password: pass1234
      name: admin

  profiles:
    active: ${ACTIVE_PROFILE:}
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db
    username: root
    password: password

  jpa:
    properties:
        hbm2ddl:
          auto: update

server:
  port: 5000